const data = {
    products:[
        {
            _id:'1',
            name:'Eletronic Part',
            category:'Part',
            image:'/images/p1.jpg',
            price: 120,
            brand: 'Parasonic',
            rating: 4.5,
            numReviews: 10,
            description: 'Good product',
        },
        {
            _id:'2',
            name:'Eletronic Part 2',
            category:'Part',
            image:'/images/p2.jpg',
            price: 100,
            brand: 'Parasonic 1',
            rating: 4.0,
            numReviews: 10,
            description: 'Good product',
        },
        {
            _id:'3',
            name:'Eletronic Part 3',
            category:'Part',
            image:'/images/p1.jpg',
            price: 120,
            brand: 'Parasonic',
            rating: 4.5,
            numReviews: 10,
            description: 'Good product',
        },
        {
            _id:'4',
            name:'Eletronic Part 4',
            category:'Part',
            image:'/images/p1.jpg',
            price: 120,
            brand: 'Parasonic',
            rating: 4.5,
            numReviews: 10,
            description: 'Good product',
        },
        {
            _id:'5',
            name:'Eletronic Part 5',
            category:'Part',
            image:'/images/p1.jpg',
            price: 120,
            brand: 'Parasonic',
            rating: 4.0,
            numReviews: 10,
            description: 'Good product',
        },
        {
            _id:'6',
            name:'Eletronic Part 6',
            category:'Part',
            image:'/images/p1.jpg',
            price: 102,
            brand: 'Parasonic',
            rating: 4.5,
            numReviews: 10,
            description: 'Good product',
        },
    ],
};

export default data;